name: Commit Alert

on: 
  push:
    branches:
      - '**'

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Full clone

      - name: Get commit details
        id: commit_info
        run: |
          commit_msg=$(git log -1 --pretty=%B)
          committer_name=$(git log -1 --pretty=%cn)
          branch_name=${GITHUB_REF#refs/heads/}
          commit_sha=$GITHUB_SHA

          echo "Commit SHA: ${commit_sha}"

          if git rev-parse "${commit_sha}^" >/dev/null 2>&1; then
              parent_sha=$(git rev-parse "${commit_sha}^")
              echo "Parent Commit SHA: ${parent_sha}"
              changed_files=$(git diff-tree --no-commit-id --name-only -r ${commit_sha} | paste -sd ', ' -)
          else
              echo "This commit is the initial commit and has no parent."
              changed_files=$(git diff-tree --no-commit-id --name-only -r ${commit_sha} | paste -sd ', ' -)
          fi

          echo "Commit Message: ${commit_msg}"
          echo "Committer Name: ${committer_name}"
          echo "Branch Name: ${branch_name}"
          echo "Changed Files: ${changed_files}"

          echo "commit_msg=${commit_msg}" >> $GITHUB_ENV
          echo "committer_name=${committer_name}" >> $GITHUB_ENV
          echo "branch_name=${branch_name}" >> $GITHUB_ENV
          echo "changed_files=${changed_files}" >> $GITHUB_ENV

      - name: Send alert
        env:  
          COMMIT_MSG: ${{ env.commit_msg }}
          COMMITTER_NAME: ${{ env.committer_name }}
          BRANCH_NAME: ${{ env.branch_name }}
          CHANGED_FILES: ${{ env.changed_files }}
        run: |
          curl --location 'https://flow.sokt.io/func/scriJhbYKJwe' \
          --header 'Content-type: application/json' \
          --data "{\"text\": \"**New Commit**:\n**Committer**: $COMMITTER_NAME\n**Commit Message**: $COMMIT_MSG\n**Branch**: $BRANCH_NAME\n**Changed Files**: $CHANGED_FILES\"}"
